insert into people (first_name, last_name, address, gender) values ('Ingaberg', 'Minchi', '18th Floor', 'Female');
insert into people (first_name, last_name, address, gender) values ('Rheba', 'Lehr', 'PO Box 93264', 'Female');
insert into people (first_name, last_name, address, gender) values ('Dewie', 'Lugsdin', 'Suite 100', 'Male');
insert into people (first_name, last_name, address, gender) values ('Walliw', 'O''Driscole', 'PO Box 44160', 'Female');
insert into people (first_name, last_name, address, gender) values ('Hewett', 'Reiners', 'PO Box 49718', 'Male');
insert into people (first_name, last_name, address, gender) values ('Lavena', 'Tuckie', 'Apt 40', 'Female');
insert into people (first_name, last_name, address, gender) values ('Sean', 'Remon', '19th Floor', 'Female');
insert into people (first_name, last_name, address, gender) values ('Batholomew', 'Merit', '2nd Floor', 'Male');
insert into people (first_name, last_name, address, gender) values ('Peder', 'Glason', 'Suite 72', 'Male');
insert into people (first_name, last_name, address, gender) values ('Ravid', 'Tuke', 'Suite 62', 'Male');
insert into people (first_name, last_name, address, gender) values ('Enid', 'Basham', 'Suite 44', 'Female');
insert into people (first_name, last_name, address, gender) values ('Annadiane', 'Gercke', '11th Floor', 'Female');
insert into people (first_name, last_name, address, gender) values ('Gabbey', 'Rodder', 'Room 793', 'Female');
insert into people (first_name, last_name, address, gender) values ('Fraser', 'Goodredge', 'Suite 15', 'Male');
insert into people (first_name, last_name, address, gender) values ('Kelsey', 'Jailler', '15th Floor', 'Male');
insert into people (first_name, last_name, address, gender) values ('Zarah', 'Kaveney', '3rd Floor', 'Female');
insert into people (first_name, last_name, address, gender) values ('Matthias', 'Elvins', 'Suite 10', 'Male');
insert into people (first_name, last_name, address, gender) values ('Nicko', 'Wolfendale', 'Room 1612', 'Male');
insert into people (first_name, last_name, address, gender) values ('Wayland', 'Tissier', 'Apt 1262', 'Male');
insert into people (first_name, last_name, address, gender) values ('Xenia', 'Rammell', 'Suite 57', 'Female');
insert into people (first_name, last_name, address, gender) values ('Antoni', 'Jowers', 'Room 274', 'Male');
insert into people (first_name, last_name, address, gender) values ('Padriac', 'Antoniades', 'PO Box 91273', 'Male');
insert into people (first_name, last_name, address, gender) values ('Dana', 'Pethick', 'Apt 785', 'Female');
insert into people (first_name, last_name, address, gender) values ('Verene', 'Kenshole', 'Apt 1698', 'Male');
insert into people (first_name, last_name, address, gender) values ('Wilbur', 'Sweetman', 'PO Box 18324', 'Male');
insert into people (first_name, last_name, address, gender) values ('Gerhard', 'Dimitrijevic', 'PO Box 55014', 'Male');
insert into people (first_name, last_name, address, gender) values ('Antoni', 'Lidstone', 'Apt 1500', 'Male');
insert into people (first_name, last_name, address, gender) values ('Tiffi', 'Hearsum', 'Apt 427', 'Female');
insert into people (first_name, last_name, address, gender) values ('Tamas', 'Tremoulet', 'Room 1402', 'Male');
insert into people (first_name, last_name, address, gender) values ('Noland', 'Plascott', 'Apt 195', 'Male');
insert into people (first_name, last_name, address, gender) values ('Darbee', 'Markovich', 'Suite 29', 'Male');
insert into people (first_name, last_name, address, gender) values ('Ellerey', 'Vedekhov', 'Suite 28', 'Male');
insert into people (first_name, last_name, address, gender) values ('Carie', 'Fullalove', 'Room 1505', 'Female');
insert into people (first_name, last_name, address, gender) values ('Deva', 'Moulson', '20th Floor', 'Female');
insert into people (first_name, last_name, address, gender) values ('Bruis', 'Wasiel', 'Room 1341', 'Male');
insert into people (first_name, last_name, address, gender) values ('Hamil', 'Towne', 'PO Box 68676', 'Male');
insert into people (first_name, last_name, address, gender) values ('Jobey', 'Aggs', 'Room 175', 'Female');
insert into people (first_name, last_name, address, gender) values ('Judd', 'Jope', 'Apt 1179', 'Male');
insert into people (first_name, last_name, address, gender) values ('Simeon', 'Minnis', 'PO Box 37586', 'Male');
insert into people (first_name, last_name, address, gender) values ('Rayna', 'Frankum', 'Room 636', 'Female');
insert into people (first_name, last_name, address, gender) values ('Nicola', 'Reolfi', '9th Floor', 'Male');
insert into people (first_name, last_name, address, gender) values ('Maryjane', 'Prestney', 'Suite 55', 'Female');
insert into people (first_name, last_name, address, gender) values ('Eryn', 'Davydzenko', 'PO Box 40939', 'Female');
insert into people (first_name, last_name, address, gender) values ('Shell', 'Hardison', '19th Floor', 'Male');
insert into people (first_name, last_name, address, gender) values ('Augusta', 'Seman', '1st Floor', 'Female');
insert into people (first_name, last_name, address, gender) values ('Babita', 'Pappi', '2nd Floor', 'Female');
insert into people (first_name, last_name, address, gender) values ('Megan', 'Dennick', 'PO Box 66853', 'Female');
insert into people (first_name, last_name, address, gender) values ('Antonio', 'Ickowicz', 'Room 425', 'Male');
insert into people (first_name, last_name, address, gender) values ('Pavla', 'Riddock', 'Room 1754', 'Female');
insert into people (first_name, last_name, address, gender) values ('Charlotte', 'Tanfield', 'Suite 67', 'Female');
