insert into people (id, first_name, last_name, address, gender) values (1, 'Harwilll', 'Cripin', 'Apt 1829', 'Male');
insert into people (id, first_name, last_name, address, gender) values (2, 'Lilith', 'Siddle', 'Suite 29', 'Female');
insert into people (id, first_name, last_name, address, gender) values (3, 'Fernanda', 'Antrobus', 'Apt 739', 'Female');
insert into people (id, first_name, last_name, address, gender) values (4, 'Chrissy', 'Hellwig', 'PO Box 10527', 'Male');
insert into people (id, first_name, last_name, address, gender) values (5, 'Brit', 'O'' Shea', 'Apt 349', 'Male');
insert into people (id, first_name, last_name, address, gender) values (6, 'Jareb', 'Crottagh', 'PO Box 98539', 'Male');
insert into people (id, first_name, last_name, address, gender) values (7, 'Christen', 'Angell', 'Suite 89', 'Female');
insert into people (id, first_name, last_name, address, gender) values (8, 'Didi', 'Hodgen', '19th Floor', 'Female');
insert into people (id, first_name, last_name, address, gender) values (9, 'Wally', 'Fairley', 'Suite 96', 'Female');
insert into people (id, first_name, last_name, address, gender) values (10, 'Maudie', 'Stork', 'Suite 22', 'Female');
insert into people (id, first_name, last_name, address, gender) values (11, 'Michele', 'Plaid', 'PO Box 51544', 'Female');
insert into people (id, first_name, last_name, address, gender) values (12, 'Libbey', 'Bucknill', '2nd Floor', 'Female');
insert into people (id, first_name, last_name, address, gender) values (13, 'Markos', 'Candelin', '15th Floor', 'Male');
insert into people (id, first_name, last_name, address, gender) values (14, 'Bradly', 'Basezzi', 'PO Box 98188', 'Male');
insert into people (id, first_name, last_name, address, gender) values (15, 'Caprice', 'Gregoratti', 'Apt 451', 'Female');
insert into people (id, first_name, last_name, address, gender) values (16, 'Kimmie', 'Allaker', 'Apt 394', 'Female');
insert into people (id, first_name, last_name, address, gender) values (17, 'Calla', 'Rief', 'PO Box 98628', 'Female');
insert into people (id, first_name, last_name, address, gender) values (18, 'Georgette', 'Branchflower', 'Room 1653', 'Female');
insert into people (id, first_name, last_name, address, gender) values (19, 'Ade', 'Langton', 'Suite 36', 'Male');
insert into people (id, first_name, last_name, address, gender) values (20, 'Russell', 'Mattiello', '5th Floor', 'Male');
insert into people (id, first_name, last_name, address, gender) values (21, 'Sybille', 'Kettel', 'Apt 1160', 'Female');
insert into people (id, first_name, last_name, address, gender) values (22, 'Chancey', 'Woolstenholmes', 'Room 447', 'Male');
insert into people (id, first_name, last_name, address, gender) values (23, 'Asher', 'Tolman', 'Room 1397', 'Male');
insert into people (id, first_name, last_name, address, gender) values (24, 'Parry', 'Spinney', 'Room 736', 'Male');
insert into people (id, first_name, last_name, address, gender) values (25, 'Joli', 'Coviello', '1st Floor', 'Female');
insert into people (id, first_name, last_name, address, gender) values (26, 'Ulick', 'Ketteringham', '9th Floor', 'Male');
insert into people (id, first_name, last_name, address, gender) values (27, 'Darlene', 'Byk', 'PO Box 88261', 'Female');
insert into people (id, first_name, last_name, address, gender) values (28, 'Vivi', 'Gypson', 'PO Box 76462', 'Female');
insert into people (id, first_name, last_name, address, gender) values (29, 'Tobey', 'Halworth', 'Room 442', 'Female');
insert into people (id, first_name, last_name, address, gender) values (30, 'Cherri', 'Pascoe', 'Apt 670', 'Female');
insert into people (id, first_name, last_name, address, gender) values (31, 'Johanna', 'Ocklin', 'Room 1166', 'Female');
insert into people (id, first_name, last_name, address, gender) values (32, 'Delbert', 'O''Doghesty', 'Apt 1237', 'Male');
insert into people (id, first_name, last_name, address, gender) values (33, 'Josiah', 'Crews', '14th Floor', 'Male');
insert into people (id, first_name, last_name, address, gender) values (34, 'Thaddeus', 'Venditto', '3rd Floor', 'Male');
insert into people (id, first_name, last_name, address, gender) values (35, 'Grazia', 'Bogart', '9th Floor', 'Female');
insert into people (id, first_name, last_name, address, gender) values (36, 'David', 'Trusler', 'Apt 956', 'Male');
insert into people (id, first_name, last_name, address, gender) values (37, 'Liam', 'Mattes', 'Apt 117', 'Female');
insert into people (id, first_name, last_name, address, gender) values (38, 'Silvie', 'Chafer', 'PO Box 2898', 'Female');
insert into people (id, first_name, last_name, address, gender) values (39, 'Vicki', 'Fenlon', 'Room 252', 'Female');
insert into people (id, first_name, last_name, address, gender) values (40, 'Chantal', 'Brimmacombe', 'Suite 88', 'Female');
insert into people (id, first_name, last_name, address, gender) values (41, 'Bernadette', 'Condell', 'PO Box 53156', 'Male');
insert into people (id, first_name, last_name, address, gender) values (42, 'Hunfredo', 'Iacomini', 'Room 1957', 'Female');
insert into people (id, first_name, last_name, address, gender) values (43, 'Madel', 'McCarly', '9th Floor', 'Female');
insert into people (id, first_name, last_name, address, gender) values (44, 'Roanna', 'Bondar', '8th Floor', 'Female');
insert into people (id, first_name, last_name, address, gender) values (45, 'Griffy', 'Gamlen', '7th Floor', 'Male');
insert into people (id, first_name, last_name, address, gender) values (46, 'Lydia', 'Hyndes', 'Apt 54', 'Female');
insert into people (id, first_name, last_name, address, gender) values (47, 'Leo', 'Mirfield', 'Suite 48', 'Male');
insert into people (id, first_name, last_name, address, gender) values (48, 'Joyous', 'McKibben', 'Suite 19', 'Female');
insert into people (id, first_name, last_name, address, gender) values (49, 'Inger', 'Ianno', 'PO Box 20465', 'Female');
insert into people (id, first_name, last_name, address, gender) values (50, 'Ginni', 'Doggrell', 'Room 401', 'Female');
